name: Deploy to Github on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: npm start:prod
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist